apiVersion: v1
kind: Service
metadata:
  name: k8s-exam-fastapi-nodeport
  labels:
    app: k8s-exam-fastapi-nodeport
spec:
  type: NodePort
  selector:
    app: k8s-exam-fastapi-deploy
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000