apiVersion: v1
kind: Service
metadata:
  name: k8s-exam-mysqldb-service
  annotations:
    kubernetes.io/cluster-ip: "10.43.0.42"  # Spécifie l'adresse IP statique
spec:
  selector:
    app: k8s-exam-mysqldb
  ports:
  - protocol: TCP
    port: 3307
    targetPort: 3306
  clusterIP: 10.43.0.42  # Adresse IP statique du service