apiVersion: v1
kind: Service
metadata:
  name: k8s-exam-mysqldb-nodeport
  annotations:
    kubernetes.io/cluster-ip: "10.43.0.42"  # Spécifie l'adresse IP statique
spec:
  type: NodePort
  selector:
    app: k8s-exam-mysqldb
  ports:
  - protocol: TCP
    port: 3307
    targetPort: 3306
    nodePort: 30000
  clusterIP: 10.43.0.42  # Adresse IP statique du service