apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k8s-exam-mysqldb
spec:
  selector:
    matchLabels:
      app: k8s-exam-mysqldb
  serviceName: k8s-exam-mysqldb
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-exam-mysqldb
    spec:
      containers:
        - name: k8s-exam-mysqldb
          image: docker.io/mysql:8.4
          ports:
            - containerPort: 3306
              protocol: TCP
          # env:
          #   - name: MYSQLDB_ROOT_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: mysqldb-root-password
          #         key: password
          envFrom:
            - secretRef:
                name: k8s-exam-mysqldb-superuser
            - secretRef:
                name: k8s-exam-mysqldb-user
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            # - name: config
            #   mountPath: etc/mysql/conf.d

      volumes:
        - name: data
          emptyDir: {}  
        # - name: config
        #   configMap:
        #     name: cm-mysqldb
        #     items:
        #       - key: mysqld.cnf
        #         path: mysqld.cnf